### ISSUE TITLE
Troubleshooting advice?

### ISSUE THREAD

**Issue by watou** [crazy-max/rocketchat-uptimerobot#1]
Thank you very much for building and sharing this integration.  I've done everything per the instructions, but I can't find evidence that Uptime Robot invoked the webhook (but it did send me an email for each of the down and up events).  Do you have any suggestions (perhaps for the README.md file) on how one can troubleshoot the integration?  Are webhooks a free Uptime Robot feature (everything I've seen suggests it is free.)

I can succeed with the example curl command given at the bottom of Rocket.Chat -> Administration -> Integrations -> Incoming Webhook Integration.  I see nothing related in the Rocket.Chat admin log.

Thanks again for building this bridge!

**Comment by crazy-max** [comment]
@watou As it's said in the [official documentation](https://rocket.chat/docs/administrator-guides/integrations/), you can debug incoming webhooks using `console` in javascript. For example in my script, you can insert the following line to have debug logging in the view-logs interface of Rocket.Chat :

![image](https://user-images.githubusercontent.com/1951866/36895876-c75e6b88-1e10-11e8-9356-a5ba96836740.png)

Btw, have you checked that the Alert Contact in the Uptime Robot settings is enabled ?

**Comment by watou** [comment]
Thank you very much for the thoughtful advice, @crazy-max.  I've check that the alert contact is enabled, the incoming webhook is enabled, the JSON payload and URL are correct, and I added the `console.log` to the script per your example.   If I have any useful follow-up I will append it here for others.  Now I wait for downtime events.... 🙂

**Comment by crazy-max** [comment]
@watou you're welcome ;)
Keep me in touch, I'll close the issue for now.

**Comment by franckadil** [comment]
@crazy-max Hi, I am having a similar issue, I tested the webhook using curl successfuly but I don't receive the alerts from uptime-robot. I followed every step as suggested.

**Comment by crazy-max** [comment]
@franckadil Hi, Your settings look like this right ? :

![image](https://user-images.githubusercontent.com/1951866/58172483-0eb38f80-7c99-11e9-8d67-8f836f69f842.png)

Have you added `?` at the end of the RocketChat URL ?

**Comment by franckadil** [comment]
@crazy-max  Yes that's exact.
![image](https://user-images.githubusercontent.com/42721509/58257957-c87a3100-7d69-11e9-8dcc-2fdf57545591.png)

Yes my url ends with ? `...[redacted]zmbxjw3Zo?`

**Comment by franckadil** [comment]
@crazy-max I found the issue, I had to edit every site and activate the new contact:
![image](https://user-images.githubusercontent.com/42721509/58259825-3d029f00-7d6d-11e9-8be4-d327f7d1c933.png)

I hope this wll help others !

**Comment by crazy-max** [comment]
@franckadil Yeah that's it :upside_down_face:

**Comment by franckadil** [comment]
@crazy-max do you know [Helpscout](https://www.helpscout.com/) ? I tried to write a webhook like you did, but I am really new at this, It would be awesome if you could build an integration for RocketChat, I know It would benefit many users! 😸 Ref: https://developer.helpscout.com/webhooks/

**Comment by crazy-max** [comment]
@franckadil Leave an issue on my [AMA](https://github.com/crazy-max/ama). I'll see if I have time to process this :dart:

**Comment by franckadil** [comment]
@crazy-max Thank you :) D'ont hesitate pm me if you need anything! I would be glad to help!
