### ISSUE TITLE
Missing message data

### ISSUE THREAD

**Issue by RowanBurgess-zz** [crazy-max/rocketchat-uptimerobot#2]
UptimeRobot triggers a message in Rocket.Chat, but the message is empty. See attached.

I've triple checked all configurations and they seem fine.

![uptime](https://user-images.githubusercontent.com/6341806/38388872-7638ff38-3914-11e8-9e60-9014a18764cd.png)

**Comment by crazy-max** [comment]
Eveything is fine with me :

![image](https://user-images.githubusercontent.com/1951866/38389417-ab8c46d6-391e-11e8-83dc-cae316bdaab5.png)

Check your ocnfiguration again, something seems wrong.

**Comment by RowanBurgess-zz** [comment]
@crazy-max I've triple checked and still no luck.

Please see attached screenshots of my configs, in case you can see anything wrong.

Please note we are using rocket on private server, not their cloud.

![rchat-config](https://user-images.githubusercontent.com/6341806/38409799-af480e5c-397a-11e8-81ae-b677fedc1b8a.jpg)
![uptime-config](https://user-images.githubusercontent.com/6341806/38409800-af60de96-397a-11e8-8e04-315d09f7a58c.jpg)

**Comment by crazy-max** [comment]
@RowanBurgess Sorry for the delay, everything seems good to me.
Can you add in the script the following line :

```js
console.log(request.content);
```

after this one :

```js
msg = buildMessage(request.content);
```

And give me the output of your RocketChat log please ?

**Comment by RowanBurgess-zz** [comment]
@crazy-max No trouble, no rush.

Please see recent and relevant snippet of rocket log attached.

[rocket.log](https://github.com/crazy-max/rocketchat-uptimerobot/files/1901964/rocket.log)

**Comment by crazy-max** [comment]
@RowanBurgess Can you comment [this line](https://github.com/crazy-max/rocketchat-uptimerobot/blob/master/src/uptimerobot-incoming.js#L64) and check if it works now ?

**Comment by RowanBurgess-zz** [comment]
@crazy-max No good. Same problem, and see log attached FYI

[rocket.log](https://github.com/crazy-max/rocketchat-uptimerobot/files/1907155/rocket.log)

**Comment by RowanBurgess** [comment]
@crazy-max Not sure if this helps, but it seems to be trying to upload a file, rather than add a comment:

![2018-05-05 09_21_42-](https://user-images.githubusercontent.com/6341806/39661412-0a7cf35c-5049-11e8-99cd-8f9cd914d1cf.png)

**Comment by RowanBurgess-zz** [comment]
@crazy-max Not sure if this helps, but it seems to be trying to upload a file, rather than add a comment:

![2018-05-05 09_21_42-](https://user-images.githubusercontent.com/6341806/39661422-293c15c0-5049-11e8-94b6-1c075776c2af.png)

**Comment by crazy-max** [comment]
@RowanBurgess Logs seems ok to me, are you using a reverse proxy ?

**Comment by RowanBurgess-zz** [comment]
@crazy-max Ah yes, we are!

**Comment by crazy-max** [comment]
@RowanBurgess What kind of reverse proxy? (apache, nginx, caddy, traefik ?)

**Comment by RowanBurgess-zz** [comment]
@crazy-max We're using Apache

**Comment by crazy-max** [comment]
Can you post your Apache config ? And can you also test without the reverse proxy ?

**Comment by crazy-max** [comment]
Closed due to inactivity.
